name: CardinalTrading
main: com.FlameKnight15.Core
version: 1.1.5-BETA
author: FlameKnight15
depends: [Vault]
commands:
  trade:
    description: Initiates a trade with another player
    usage: /trade <player>